### ISSUE TITLE
Pattern #1000 is missing for guns

### ISSUE THREAD

**Issue by adbok001** [chescos/csgo-fade-percentage-calculator#12]
In [L116](https://github.com/chescos/csgo-fade-percentage-calculator/blob/master/src/modules/FadeCalculator.ts#L116) of `FadeCalculator.ts` you stop at pattern ID 999, but pattern ID 1000 can be obtained through trade-ups, so it is missing for all non-knife weapons.

**Comment by chescos** [comment]
Thanks for reporting this issue, seed `1000` is now available for all guns.
