### ISSUE TITLE
Feature: Pattern Index Ranking

### ISSUE THREAD

**Issue by GODrums** [chescos/csgo-fade-percentage-calculator#19]
While top rankings of Case Hardened patterns are identified by their index, Fade is still only classified after percentages.

I would like to propose an option to create a pattern index ranking for Fade skins. This would allow to define top patterns, when percentages become unclear.

As an example let's assume you want to buy the lowest fade Karambit. Websites will not distinguish after the first decimal place, so there are 7 "top" 80.0% patterns (93, 341, 403, 575, 636, 897, 910), although 575 should be the clear number 1 pattern with 80.007%.

A simple ranking implementation accounting for lowest and highest fade could look like this:
```
interface FadeRanking {
  seed: number,
  percentage: number,
  ranking: number
}

  getFadePercentageRanking(weapon: string, seed: number): FadeRanking {
    const percentages = this.getFadePercentages(weapon);
    const ranking = [...percentages].sort((a, b) => a.percentage - b.percentage).findIndex((el) => el.seed === seed);


    return ({
      seed: percentages[seed].seed,
      percentage: percentages[seed].percentage,
      ranking: Math.min(ranking+1, 999-ranking)
    });
  }
```

I would love to hear your thoughts and discuss this idea further or help with the implementation.

**Comment by chescos** [comment]
I'd be open to adding this. I wouldn't add a separate method for this though, I think it makes more sense to just extend the `FadePercentage` interface with a `ranking` property, like this:

```ts
interface FadePercentage {
  seed: number,
  percentage: number,
  ranking: number,
}
```

What do you think?

**Comment by GODrums** [comment]
That seems like an adequate static alternative. 

I am hopeful this can prove to be a very useful improvement to many skin collectors.

**Comment by chescos** [comment]
Do you want to submit a PR for this?

**Comment by GODrums** [comment]
Thanks for the opportunity!

I just opened a PR with my suggested changes and the updated JSON (see #22).
Feel free to edit my code after your free will.

**Comment by chescos** [comment]
Thanks, merged it. I'll release a package version with the new ranking feature soon.

**Comment by InspectorSkinner** [comment]
With a skin such as the MP7 Fade, I currently feel as if there is a large discrepancy between the fade percentages between 99%-100%, where perhaps the rotation value makes it difficult to tell.
