### ISSUE TITLE
ESM version doesn't work

### ISSUE THREAD

**Issue by wavpro** [chescos/csgo-fade-percentage-calculator#35]
When importing the project with ES6 imports, the dist/esm version is used. This version uses `import` to import it's modules, but here lies the problem. Node only let's you use this if the package has `"type": "module"` specified in it's `package.json`, which this project does not. So if you try to import it you get the following error:

```
import FadeCalculatorModule from './modules/FadeCalculator';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

**Comment by chescos** [comment]
Fixed via #38
