### ISSUE TITLE
Failing to map ★ Specialist Gloves | Fade. 

### ISSUE THREAD

**Issue by yusuf-murodov-gamerpay** [chescos/csgo-fade-percentage-calculator#50]
Failing to get fade percentage for this skin type ★ Specialist Gloves | Fade. Can you guys add mapping and support for this skin?
![image](https://github.com/user-attachments/assets/042028c3-fd82-41ce-9ce5-688947da8443)

**Comment by chescos** [comment]
Unfortunately, the Fade percentage for gloves cannot be calculated with the method we're using. The pattern movement is not predictable for us.
